name: Test, lint & build

on:
  - push

env:
  DB_NAME: shy_llc

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    services:
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shy_llc
        ports:
          - 5432:5432
        options: >-
          --hostname=shy_db
          --health-cmd="pg_isready -U postgres -d shy_llc"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: useblacksmith/setup-go@v6
        with:
          go-version: "1.23.2"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
          golangci-lint version

      - name: Install templ
        run: |
          go install github.com/a-h/templ/cmd/templ@v0.3.819
          templ --help

      - name: Install TailwindCSS
        run: |
          echo "Installing TailwindCSS for x64 architecture..."
          mkdir -p downloaded
          curl -sL -o downloaded/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.15/tailwindcss-linux-x64
          chmod +x downloaded/tailwindcss
          echo "$PWD/downloaded" >> $GITHUB_PATH

      - name: Verify TailwindCSS installation
        run: |
          tailwindcss -h


      - name: Download Go dependencies
        run: go mod download

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres -d shy_llc; do
            echo "Waiting for postgres..."
            sleep 1
          done

      - name: Test generated files are up to date
        run: |
          go generate ./...
          make generate
          git diff --exit-code

      - name: Run custom linter
        run: make build-iota-linter && make run-iota-linter

      - name: Check migrations collect idempotence
        run: |
          make migrate collect
          git status --porcelain migrations/
          if [ -n "$(git status --porcelain migrations/)" ]; then
            echo "Error: make migrate collect produced changes, please run 'make migrate collect' and commit the changes"
            git status --porcelain migrations/
            exit 1
          fi

      - name: Test Makefile targets
        # running migrations and seeds twice to verify that they are idempotent
        run: |
          make migrate up
          make migrate up
          make seed
          make seed
          make css

      - name: Run go vet && tests
        run: |
          make generate
          git diff --exit-code
          go vet ./...
          go test -v ./...

      - name: Test database migrate down
        run: |
          make migrate down
